from . import db
from flask_login import UserMixin, current_user
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url_cover = db.Column(db.String(10000))
    mobilebg = db.Column(db.String(10000))
    introbg = db.Column(db.String(10000))
    fontcolor = db.Column(db.String(10000))
    autore = db.Column(db.String(150))
    titolo = db.Column(db.String(150))
    genere = db.Column(db.String(150))
    trama = db.Column(db.String(10000))
    date_start = db.Column(db.String(150))
    date_end = db.Column(db.String(150))
    valutazione = db.Column(db.Integer)
    spicy = db.Column(db.Integer)
    lacrime = db.Column(db.Integer)
    favourite_Charac = db.Column(db.String(150))
    hated_Charac = db.Column(db.String(150))
    favourite_Scene = db.Column(db.String(10000))
    best_Phrase = db.Column(db.String(10000))
    review = db.Column(db.String(10000))
    tipo = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class Wish_List(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url_cover = db.Column(db.String(10000))
    autore = db.Column(db.String(150))
    titolo = db.Column(db.String(150))
    costo = db.Column(db.String(100000))
    tipo = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class Theme(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    theme_light_primary = db.Column(db.String(10000))
    theme_light_primary_loading = db.Column(db.String(10000))
    theme_light_secondary = db.Column(db.String(10000))
    theme_light_accent = db.Column(db.String(10000))
    theme_light_font_color = db.Column(db.String(10000))
    theme_light_extra = db.Column(db.String(10000))
    theme_light_font_color_hover = db.Column(db.String(10000))
    theme_dark_primary = db.Column(db.String(10000))
    theme_dark_primary_loading = db.Column(db.String(10000))
    theme_dark_secondary = db.Column(db.String(10000))
    theme_dark_accent = db.Column(db.String(10000))
    theme_dark_font_color = db.Column(db.String(10000))
    theme_dark_extra = db.Column(db.String(10000))
    theme_dark_font_color_hover = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')
    wish_list = db.relationship('Wish_List')
    theme = db.relationship('Theme')